export { default as Home } from './HomePage'
export { default as Main } from './MainPage'
export { default as Board } from './BoardPage'
export { default as Profile } from './Profile'
export { default as NoMatch } from './NoMatch'
