export { default as Home } from './Home'
export { default as Main } from './Main'
export { default as Board } from './Board'
export { default as Profile } from './Profile'
export { default as NoMatch } from './NoMatch'
