export { default as Home } from './HomePage'
export { default as Main } from './Main/MainPage'
export { default as Board } from './Board/BoardPage'
export { default as Profile } from './Profile/ProfilePage'
export { default as SignIn } from './SignIn/SignInPage'
export { default as SignUp } from './SignUp/SignUpPage'
export { default as NoMatch } from './NoMatchPage'
